### ISSUE TITLE
_moderngl.Error: data size mismatch on 3D-FRONT data

### ISSUE THREAD

**Issue by hyuk199** [nv-tlabs/ATISS#28]
I've tried to run the preprocess_data.py script. I met the error `_moderngl.Error: data size mismatch 4194304 != 104857` on 3aa40ca2-8d84-4fc1-b2b8-ce2234c45f60 3D-FRONT json.
```
Traceback (most recent call last):
  File "preprocess_data.py", line 278, in <module>
    main(sys.argv[1:])
  File "preprocess_data.py", line 268, in main
    render(
  File "C:\Users\user\Documents\Workspace\ATISS\scripts\utils.py", line 199, in render
    scene.add(r)
  File "C:\Users\user\miniconda3\envs\atiss\lib\site-packages\simple_3dviz\scenes.py", line 60, in add
    renderable.init(self._ctx)
  File "C:\Users\user\miniconda3\envs\atiss\lib\site-packages\simple_3dviz\renderables\textured_mesh.py", line 160, in init
    self.material = self._material
  File "C:\Users\user\miniconda3\envs\atiss\lib\site-packages\simple_3dviz\renderables\textured_mesh.py", line 203, in material
    self._texture = self._prog.ctx.texture(
  File "C:\Users\user\miniconda3\envs\atiss\lib\site-packages\moderngl\__init__.py", line 1771, in texture
    res.mglo, res._glo = self.mglo.texture(size, components, data, samples, alignment, dtype, internal_format or 0)
_moderngl.Error: data size mismatch 4194304 != 1048576
```
I really don't know what is problem. Has anyone else had this problem? Please help me.

**Comment by paschalidoud** [comment]
Hi @hyuk199,

Can you provide the simple-3dviz version and moderngl version you are using?

Best,
Despoina

**Comment by paschalidoud** [comment]
Since this thread has been inactive for a while, I am closing the issue for now, but feel free to reopen it if you have any further issues.

Cheers,
Despi
