### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by k-bobin** [nv-tlabs/ATISS#35]
Every time I run the code below:
`(atiss) bobinkim@Bobinui-MacbookAir scripts % python3 pickle_threed_future_dataset.py path_to_output_dir /Users/bobinkim/ATISS/dataset/3D-FRONT /Users/bobinkim/ATISS/dataset/3D-FUTURE-model /Users/bobinkim/ATISS/dataset/3D-FUTURE-model/model_info.json --dataset_filtering threed_front_bedroom`

the error pops up like below:
`Applying threed_front_bedroom filtering
Loading dataset  6811 /  6812
Traceback (most recent call last):
  File "/Users/bobinkim/ATISS/scene_synthesis/datasets/threed_front_scene.py", line 339, in corners
    bbox_vertices = np.load(self.path_to_bbox_vertices, mmap_mode="r")
  File "/Users/bobinkim/miniforge3/envs/atiss/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bobinkim/ATISS/dataset/3D-FUTURE-model/e3560eb3-d4e1-4add-8b51-b3dd5ec6943b/bbox_vertices.npy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bobinkim/ATISS/scene_synthesis/datasets/threed_front_scene.py", line 261, in raw_model
    return trimesh.load(
  File "/Users/bobinkim/miniforge3/envs/atiss/lib/python3.8/site-packages/trimesh/exchange/load.py", line 116, in load
    ) = parse_file_args(file_obj=file_obj,
  File "/Users/bobinkim/miniforge3/envs/atiss/lib/python3.8/site-packages/trimesh/exchange/load.py", line 630, in parse_file_args
    raise ValueError('string is not a file: {}'.format(file_obj))
ValueError: string is not a file: /Users/bobinkim/ATISS/dataset/3D-FUTURE-model/e3560eb3-d4e1-4add-8b51-b3dd5ec6943b/raw_model.obj

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pickle_threed_future_dataset.py", line 127, in <module>
    main(sys.argv[1:])
  File "pickle_threed_future_dataset.py", line 101, in main
    scenes_dataset = ThreedFront.from_dataset_directory(
  File "/Users/bobinkim/ATISS/scene_synthesis/datasets/threed_front.py", line 179, in from_dataset_directory
    return cls([s for s in map(filter_fn, scenes) if s], bounds)
  File "/Users/bobinkim/ATISS/scene_synthesis/datasets/threed_front.py", line 179, in <listcomp>
    return cls([s for s in map(filter_fn, scenes) if s], bounds)
  File "/Users/bobinkim/ATISS/scene_synthesis/datasets/common.py", line 211, in inner
    s = next(fs)(s)
  File "/Users/bobinkim/ATISS/scene_synthesis/datasets/common.py", line 108, in inner
    return scene if scene.bbox[1][axis] <= max_size else False
  File "/Users/bobinkim/ATISS/scene_synthesis/datasets/threed_front_scene.py", line 473, in bbox
    corners = np.vstack([corners, f.corners()])
  File "/Users/bobinkim/ATISS/scene_synthesis/datasets/threed_front_scene.py", line 341, in corners
    bbox_vertices = np.array(self.raw_model().bounding_box.vertices)
  File "/Users/bobinkim/ATISS/scene_synthesis/datasets/threed_front_scene.py", line 273, in raw_model
    v, f = load_obj(self.raw_model_path)
  File "/Users/bobinkim/ATISS/scene_synthesis/datasets/threed_front_scene.py", line 37, in load_obj
    fin = open(fn, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bobinkim/ATISS/dataset/3D-FUTURE-model/e3560eb3-d4e1-4add-8b51-b3dd5ec6943b/raw_model.obj'`

The exact same error occurs when running preprocess.py as well.

This might be a simple  and easy question. Feel free to share your way to resolve this issue or you opinion

**Comment by Iv-T** [comment]
@k-bobin Did you solve this issue? I am having the same error when I run preprocess.py. Can you share how you solved this?

**Comment by k-bobin** [comment]
There are some missing 3D-FUTURE model dataset. Unless you update a black_list.txt depending on your current dataset, you would get the same error.
